
# Cloudflare Pages configuration

[build]
command = "npm install && npm run build"

[site]
bucket = "dist"

[build.environment]
NODE_VERSION = "18"

# New Pages configuration syntax
pages_build_output_dir = "dist"
